import Image from 'next/image';
import Link from 'next/link';

import styles from './HomepageNonprofit.module.scss';

export default function HomepageNonprofit() {
  return (
    <div className={styles.cta}>
      <div className="wp-block-media-text has-media-on-the-left is-stacked-on-mobile white-image-left">
        <div className="wp-block-media-text__content">
          <h2 className="wp-block-heading">Serving as a Nonprofit</h2>
          <p>Cal Poly Partners is a nonprofit, self-supporting entity. Unlike the university, we receive no state funding. Every dollar generated by our activities goes back to Cal Poly, providing vital resources to the campus community.
          </p>
          <p>
            <Link legacyBehavior href="/mission-vision-values/">
              <a title="Mission, Vision and Values">
                Mission, Vision and Values
              </a>
            </Link>
          </p>
        </div>
        <figure className="wp-block-media-text__media">
          <Image
            src="/home/cal-poly-students-packaging-chocolate-production-lab.webp"
            width={980}
            height={630}
            alt="Cal Poly students in hairnets and gloves packaging chocolate bars on trays in a food production lab."
            sizes="(max-width: 768px) 70vw, (max-width: 1200px) 50vw, 30vw"
            quality={70}
            style={{ width: '100%', height: 'auto', objectFit: 'cover' }}
          />
        </figure>
      </div>
    </div>
  );
}
